### PR TITLE
Fix concurrency bug in HugeGraph

### PR DESCRIPTION
**Pull request by knutwalker**
When multiple threads started multiple nested iterations it could happen that those iterations ran on shared cursors and that it would throw around NPEs, AIOOBEs or just produce wrong data.

The proposed solution is to not use implicit pooling and reuse but to explicitly request new iterator instances that are safe to use independently from another. This is more or less the same solution that @pstutz proposed in #385.

### CODE REVIEW

**Comment by pstutz** [comment]
I have these changes ready for 3.1 at home.

**Comment by pstutz** [comment]
The reason I didn't send a PR test is because they weren't an improvement on HugeGraph in the benchmarks. If the current implementation is not safe that would explain why. :)

**Comment by jexp** [comment]
@pstutz so you can send in your third change now?

**Comment by pstutz** [comment]
@jexp: I could, but I mainly have a similar same change for LightGraph as well. Not sure of the semantics now, does this mean that by default all graphs are only safe for single-threaded access and one needs a copy for each thread that concurrently iterates to safely access it? I think it would be reasonable to make that the default, and it would allow for a simpler implementation than what I originally did with a separate extra class for each graph implementation that reuses its cursors.

**Comment by knutwalker** [comment]
@pstutz I agree, I'd like to go that route to have on single-threaded access by default, makes it simpler and more explicit.

**Pull request merged**
