### PR TITLE
Added A* Implementation for Shortest Path

### PR DESCRIPTION
**Pull request by smadurange**
Heuristic function is for geospatial distances.
Tested on a graph of about 9000 nodes and found to be faster than Dijkstra implementation by at least 2 orders of magnitude.

@mneedham built against 3.2 upstream branch. Thanks for the review.

### CODE REVIEW

**Comment by smadurange** [comment]
@mknblch Great. Sorry about the formatting, it looked okay in my Eclipse editor. Also, thanks for your great work, we got amazing performance out of it. We will continue to contribute.

**Comment by mneedham** [comment]
@smadurange shall I just merge this in by copy/pasting the file changes on this PR?

**Comment by smadurange** [comment]
@mneedham Can you please merge the branch the now? I thought it was merged and I deleted the branch mistake. Please check if you can merge now.

**Comment by mneedham** [comment]
@smadurange merged in now

**Comment by mneedham** [comment]
@smadurange Can you fill in the Neo4j CLA for your contribution. The instructions are here: https://neo4j.com/developer/cla/

**Comment by smadurange** [comment]
@mneedham  I sent the email to cla@neotechnology.com with the attached cla as per instructions. Let me know if that's alright.

**Comment by mneedham** [comment]
@smadurange Perfect. Thanks!

**Comment by smadurange** [comment]
@mneedham You're welcome. If there's any documentation you'd like me to update let me know. I do plan to generalize the implementation as well.

**Comment by jexp** [comment]
@smadurange would you mind joining neo4j.com/slack and ping me there? Thank you!

**Comment by smadurange** [comment]
@jexp Pinged you on slack.

**Pull request merged**
