### PR TITLE
Fix LPA writeback syntax

### PR DESCRIPTION
**Pull request by tomasonjo**
Moved direction parameter to config map for lpa writeback to be consistent with lpa.stream and all the rest

### CODE REVIEW

**Comment by jexp** [comment]
How do we handle backward compatibility here?

Esp. for things like blog posts / sandboxes / graphgists using the existing syntax ...

**Comment by tomasonjo** [comment]
Does it make sense to have both options and then slowly deprecate the

**Comment by jexp** [comment]
Yes.

**Comment by mneedham** [comment]
@tomasonjo this one is still a WIP if I understood correctly?

**Comment by tomasonjo** [comment]
Yes the issue is with backwards compatibility for all guides, tutorials, etc... 

we can't have two procedures with the same name, so I am kinda stuck, because I don't want to introduce a new name for labelPropagation writeback algorithm.

What I could do is to locate all guides and tutorials made by Neo and myself and then correct them once we would apply this PR... other then that not sure what could be the alternative

**Comment by mneedham** [comment]
I put in a commit for this that handles backwards compatibility in the latest release

**Comment by mneedham** [comment]
I put in a commit for this that handles backwards compatibility in the latest release

**Pull request closed without merging**
