### PR TITLE
[WIP] Huge relationship scanning

### PR DESCRIPTION
**Pull request by knutwalker**
Supersedes: #650 
Todo:
 - [Degree preloading](https://github.com/neo4j-contrib/neo4j-graph-algorithms/pull/650#issuecomment-421134308)
 - Maybe [Multiple node properties](https://github.com/neo4j-contrib/neo4j-graph-algorithms/pull/658)
 - Apply parallel scanning to nodes as well (together with degree preloading)
 - testing on a big box

### CODE REVIEW

**Comment by jexp** [comment]
@knutwalker I did the testing with a huge store. It worked with Zing VM.
We still have work to do for the algorithms.

Can you rebase this, then I can merge it and perhaps turn the TODOs into separate issues/PRs?

**Comment by jexp** [comment]
@knutwalker please rebase it, so we can merge it in

**Comment by knutwalker** [comment]
@jexp rebased

**Comment by mneedham** [comment]
@knutwalker need to rebase again - I guess after node loader was merged!

**Comment by knutwalker** [comment]
This one was included in #771, which was the one being merged, so I'll just close this one then.

**Pull request closed without merging**
