### PR TITLE
Improve randomness for LPA

### PR DESCRIPTION
**Pull request by knutwalker**
This one includes #857, so that one should be merged first.

### CODE REVIEW

**Comment by jexp** [comment]
Thanks a lot Paul.

**Comment by jexp** [comment]
@knutwalker we should see in which other algorithms we could/should use those new local random generators.

How does the performance compare between LPA on Huge vs. Heavy?

**Comment by knutwalker** [comment]
@jexp Louvain and Infomap could make use of the random generators.

I've benchmarked the performance of the plain iterators, but not yet of the complete Louvain impls

**Comment by knutwalker** [comment]
@jexp seems like the HugeLPA doesn't do too well and the changes introduced a regression to the regular LPA as well

Screenshot_2019-04-03 JMH Visualizer

**Comment by jexp** [comment]
Did  you flamegraph it?

Inlining with inheritance?

**Comment by knutwalker** [comment]
I've got some here 
[lpa-flamegraphs.zip](https://github.com/neo4j-contrib/neo4j-graph-algorithms/files/3043872/lpa-flamegraphs.zip)

**Comment by szarnyasg** [comment]
@knutwalker I was recently looking into LPA again, for using it in the LDBC Graphalytics benchmark. LPA docs says that:
> At every iteration of propagation, each node updates its label to the one that the maximum numbers of its neighbours belongs to. Ties are broken uniformly and randomly.
The Graphalytics benchmark requires deterministic execution, so in case of a tie, the smallest label wins.

According to the [spec](https://ldbc.github.io/ldbc_graphalytics_docs/graphalytics_spec.pdf):
image

Do you think it's possible to support such an approach to achieve determinism?

**Comment by jexp** [comment]
We could add an option for that. 
Default to random option for smallest

**Pull request merged**
